### ISSUE TITLE
aclocal-1.13 and libtool new version is require which is bad ..get rid of these problems

### ISSUE THREAD

**Issue by gauravaror** [xapian/xapian-evaluation#6]

**Comment by ojwb** [comment]
Was the problem that these versions were very new back in May 2013, so not readily available via packages for most people?

If so, the intervening 3+ years probably mean this is no longer an issue.

**Comment by ojwb** [comment]
And another 4 years...

I think we can safely close this now.  If there's still a problem here please reopen and explain what's left to do.
